name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node_version: [ "20" ]
        java: [ "17" ]
      fail-fast: false
    env:
      NX_VERBOSE_LOGGING: "true"
      NX_MAVEN_CLI: "mvn"
      NX_MAVEN_CLI_OPTS: "--no-transfer-progress -Dmaven.plugin.validation=VERBOSE"
    runs-on: ${{ matrix.os }}


    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - run: npm ci --legacy-peer-deps
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx build m-sb-app

      - run: npx nx run-many -t build --parallel --skip-nx-cache

